CREATE TABLE IF NOT EXISTS rsvp (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    guests INTEGER NOT NULL DEFAULT 1,
    menu_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);